//= "../blocks/menu/menu.js"
//= "../blocks/header/header.js"
//= "../blocks/input/input.js"
//= "../blocks/product/product.js"
//= "../blocks/about/about.js"
//= "../blocks/reviews/reviews.js"
//= "../blocks/contacts/contacts.js"
